package backend

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"

	"github.com/stellar/go/build"
	"github.com/stellar/go/clients/horizon"
	"github.com/stellar/go/clients/horizonclient"
	"github.com/stellar/go/keypair"
	"github.com/stellar/kelp/gui/model"
	"github.com/stellar/kelp/plugins"
	"github.com/stellar/kelp/support/toml"
	"github.com/stellar/kelp/trader"
)

const publicTestnetHorizon = "https://horizon-testnet.stellar.org"
const issuerSeed = "SANPCJHHXCPRN6IIZRBEQXS5M3L2LY7EYQLAVTYD56KL3V7ABO4I3ISZ"

var centralizedPricePrecisionOverride = int8(6)
var centralizedVolumePrecisionOverride = int8(1)
var centralizedMinBaseVolumeOverride = float64(30.0)
var centralizedMinQuoteVolumeOverride = float64(10.0)

func (s *APIServer) autogenerateBot(w http.ResponseWriter, r *http.Request) {
	kp, e := keypair.Random()
	if e != nil {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("error generating keypair: %s\n", e)))
		return
	}

	bot := model.MakeAutogeneratedBot()
	go setupAccount(kp.Address(), kp.Seed(), bot.Name)

	_, e = s.kos.Blocking("mkdir", "mkdir -p "+s.configsDir)
	if e != nil {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("error running mkdir command for configsDir: %s\n", e)))
		return
	}

	_, e = s.kos.Blocking("mkdir", "mkdir -p "+s.logsDir)
	if e != nil {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("error running mkdir command for logsDir: %s\n", e)))
		return
	}

	filenamePair := bot.Filenames()
	sampleTrader := makeSampleTrader(kp.Seed())
	traderFilePath := fmt.Sprintf("%s/%s", s.configsDir, filenamePair.Trader)
	log.Printf("writing autogenerated bot config to file: %s\n", traderFilePath)
	e = toml.WriteFile(traderFilePath, sampleTrader)
	if e != nil {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("error writing trader toml file: %s\n", e)))
		return
	}

	sampleBuysell := makeSampleBuysell()
	strategyFilePath := fmt.Sprintf("%s/%s", s.configsDir, filenamePair.Strategy)
	log.Printf("writing autogenerated strategy config to file: %s\n", strategyFilePath)
	e = toml.WriteFile(strategyFilePath, sampleBuysell)
	if e != nil {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("error writing strategy toml file: %s\n", e)))
		return
	}

	botJson, e := json.Marshal(*bot)
	if e != nil {
		w.WriteHeader(http.StatusInternalServerError)
		w.Write([]byte(fmt.Sprintf("unable to serialize bot: %s\n", e)))
		return
	}

	w.WriteHeader(http.StatusOK)
	w.Write(botJson)
}

func setupAccount(address string, signer string, botName string) {
	hclient := horizonclient.DefaultTestNetClient
	txSuccess, e := hclient.Fund(address)
	if e != nil {
		log.Printf("error funding address %s for bot '%s': %s\n", address, botName, e)
		return
	} else {
		log.Printf("successfully funded account %s for bot '%s': %s\n", address, botName, txSuccess.TransactionSuccessToString())
	}

	client := horizon.DefaultTestNetClient
	txn, e := build.Transaction(
		build.SourceAccount{AddressOrSeed: address},
		build.AutoSequence{SequenceProvider: client},
		build.TestNetwork,
		build.Trust("COUPON", "GBMMZMK2DC4FFP4CAI6KCVNCQ7WLO5A7DQU7EC7WGHRDQBZB763X4OQI"),
		build.Payment(
			build.Destination{AddressOrSeed: address},
			build.CreditAmount{Code: "COUPON", Issuer: "GBMMZMK2DC4FFP4CAI6KCVNCQ7WLO5A7DQU7EC7WGHRDQBZB763X4OQI", Amount: "1000.0"},
			build.SourceAccount{AddressOrSeed: "GBMMZMK2DC4FFP4CAI6KCVNCQ7WLO5A7DQU7EC7WGHRDQBZB763X4OQI"},
		),
	)
	if e != nil {
		log.Printf("cannot create trustline transaction for account %s for bot '%s': %s\n", address, botName, e)
		return
	}
	txnS, e := txn.Sign(signer, issuerSeed)
	if e != nil {
		log.Printf("cannot sign trustline transaction for account %s for bot '%s': %s\n", address, botName, e)
		return
	}
	txn64, e := txnS.Base64()
	if e != nil {
		log.Printf("cannot convert trustline transaction to base64 for account %s for bot '%s': %s\n", address, botName, e)
		return
	}
	resp, e := client.SubmitTransaction(txn64)
	if e != nil {
		log.Printf("error submitting change trust transaction for address %s for bot '%s': %s\n", address, botName, e)
		return
	}
	log.Printf("successfully added trustline for address %s for bot '%s': %v\n", address, botName, resp)
}

func makeSampleTrader(seed string) *trader.BotConfig {
	return trader.MakeBotConfig(
		"",
		seed,
		"XLM",
		"",
		"COUPON",
		"GBMMZMK2DC4FFP4CAI6KCVNCQ7WLO5A7DQU7EC7WGHRDQBZB763X4OQI",
		300,
		0,
		5,
		"both",
		0,
		0,
		publicTestnetHorizon,
		nil,
		&trader.FeeConfig{
			CapacityTrigger: 0.8,
			Percentile:      90,
			MaxOpFeeStroops: 5000,
		},
		&centralizedPricePrecisionOverride,
		&centralizedVolumePrecisionOverride,
		&centralizedMinBaseVolumeOverride,
		&centralizedMinQuoteVolumeOverride,
	)
}

func makeSampleBuysell() *plugins.BuySellConfig {
	return plugins.MakeBuysellConfig(
		0.001,
		0.001,
		0.0,
		0.0,
		true,
		10.0,
		"exchange",
		"kraken/XXLM/ZUSD",
		"fixed",
		"1.0",
		[]plugins.StaticLevel{
			plugins.StaticLevel{
				SPREAD: 0.0010,
				AMOUNT: 100.0,
			}, plugins.StaticLevel{
				SPREAD: 0.0015,
				AMOUNT: 100.0,
			}, plugins.StaticLevel{
				SPREAD: 0.0020,
				AMOUNT: 100.0,
			}, plugins.StaticLevel{
				SPREAD: 0.0025,
				AMOUNT: 100.0,
			},
		},
	)
}
