package model

import (
	"fmt"
	"strings"
)

// Bot represents a kelp bot instance
type Bot struct {
	Name     string `json:"name"`
	Strategy string `json:"strategy"`
	Running  bool   `json:"running"`
	Test     bool   `json:"test"`
	Warnings uint16 `json:"warnings"`
	Errors   uint16 `json:"errors"`
}

// MakeAutogeneratedBot factory method
func MakeAutogeneratedBot() *Bot {
	return &Bot{
		Name:     "George the Auspicious Octopus",
		Strategy: "buysell",
		Running:  false,
		Test:     true,
		Warnings: 0,
		Errors:   0,
	}
}

// FilenamePair represents the two config filenames associated with a bot
type FilenamePair struct {
	Trader   string
	Strategy string
}

// Filename where we should save bot file
func (b *Bot) Filenames() *FilenamePair {
	converted := strings.ToLower(strings.ReplaceAll(b.Name, " ", "_"))
	return &FilenamePair{
		Trader:   fmt.Sprintf("%s__trader.%s", converted, "cfg"),
		Strategy: fmt.Sprintf("%s__strategy_%s.%s", converted, b.Strategy, "cfg"),
	}
}
