package model

// Bot represents a kelp bot instance
type Bot struct {
	Name     string `json:"name"`
	Running  bool   `json:"running"`
	Test     bool   `json:"test"`
	Warnings uint16 `json:"warnings"`
	Errors   uint16 `json:"errors"`
}

// MakeAutogeneratedBot factory method
func MakeAutogeneratedBot() *Bot {
	return &Bot{
		Name:     "George the Auspicious Octopus",
		Running:  false,
		Test:     true,
		Warnings: 0,
		Errors:   0,
	}
}
