package kraken

import (
	"github.com/lightyeario/kelp/support/exchange/api"
	"github.com/lightyeario/kelp/support/exchange/api/assets"
	"github.com/lightyeario/kelp/support/exchange/api/number"
)

// GetTickerPrice impl.
func (k krakenExchange) GetTickerPrice(pairs []assets.TradingPair) (map[assets.TradingPair]api.Ticker, error) {
	pairsMap, e := assets.TradingPairs2Strings(k.assetConverter, k.delimiter, pairs)
	if e != nil {
		return nil, e
	}

	resp, e := k.api.Ticker(values(pairsMap)...)
	if e != nil {
		return nil, e
	}

	priceResult := map[assets.TradingPair]api.Ticker{}
	for _, p := range pairs {
		pairTickerInfo := resp.GetPairTickerInfo(pairsMap[p])
		priceResult[p] = api.Ticker{
			AskPrice:  number.MustFromString(pairTickerInfo.Ask[0], k.precision),
			AskVolume: number.MustFromString(pairTickerInfo.Ask[1], k.precision),
			BidPrice:  number.MustFromString(pairTickerInfo.Bid[0], k.precision),
			BidVolume: number.MustFromString(pairTickerInfo.Bid[1], k.precision),
		}
	}

	return priceResult, nil
}

// values gives you the values of a map
// TODO 2 - move to autogenerated generic function
func values(m map[assets.TradingPair]string) []string {
	values := []string{}
	for _, v := range m {
		values = append(values, v)
	}
	return values
}
